### ISSUE TITLE
OKTA Backend Module Incorrect NPM path

### ISSUE THREAD

**Issue by billabongrob** [seatgeek/backstage-plugins#45]
The documentation states to use `@seatgeek/catalog-backend-module-okta` but the package in npm is `@seatgeek/backstage-plugin-catalog-backend-module-okta`

**Comment by zhammer** [comment]
thanks for letting us know. want to put up a PR for this? if not i can!

**Comment by billabongrob** [comment]
Hi @zhammer  sorry about that, it's in #46

**Comment by billabongrob** [comment]
Fix by #46
