### ISSUE TITLE
(slack-catalog-backend): please upgrade the dependency backend-common, currently: ^0.20.1 which is quite outdated

### ISSUE THREAD

**Issue by skfarhat** [seatgeek/backstage-plugins#57]
# Description 

> (slack-catalog-backend): please upgrade the dependency backend-common, currently: ^0.20.1 which is quite outdated

At the time of writing `@backstage/backend-common` is on `0.22.0`: 
https://www.npmjs.com/package/@backstage/backend-common

**Comment by zhammer** [comment]
hey, just bumped some deps to latest which you should see reflected in `@seatgeek/backstage-plugin-slack-catalog-backend@1.1.1`

any specific deps that are an issue for you? please submit a PR if you would like any of these changes on a quicker cadence. we're just now getting around to migrating our backstage instance to the new backend.
