### ISSUE TITLE
Logger issue with plugin-slack-catalog-backend

### ISSUE THREAD

**Issue by AndreaBacquele** [seatgeek/backstage-plugins#71]
Hi! :hand: 
We are using your `plugin-slack-catalog-backend`
We have a type error when we use `fromConfig()`in our backend module. 
With Backstage config in our createBackendModule, we use ` logger: coreServices.logger,`.  
But we have this type error: `Argument of type 'LoggerService' is not assignable to parameter of type 'Logger'. `

Would you happen to have a solution? We need to update our Backstage version to the 1.31 and they start to deprecate `loggerToWinstonLogger` method. 

Thanks in advance

**Comment by bbckr** [comment]
Thanks for raising @AndreaBacquele. Opening a PR and will have the team review it once they are online.

**Comment by AndreaBacquele** [comment]
Thank you @bbckr !!!

**Comment by bbckr** [comment]
Leaving reopened until the package is published, will be version 2.0.0

**Comment by AndreaBacquele** [comment]
Just to keep my team updated: Do you have an idea when the package will be published? :)

**Comment by bbckr** [comment]
> Just to keep my team updated: Do you have an idea when the package will be published? :)

This was published yesterday https://github.com/seatgeek/backstage-plugins/releases/tag/%40seatgeek%2Fbackstage-plugin-slack-catalog-backend%402.0.0
